version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Build started"
      - aws cloudformation validate-template --template-body file://template.yaml

artifacts:
  files:
    - template.yaml
